
all: report1.pdf report2.pdf

report1.pdf: report1.tex
	pdflatex report1
	pdflatex report1
	pdflatex report1

report2.pdf: report2.tex
	pdflatex report2
	pdflatex report2
	pdflatex report2

clean: 
	\rm -f *.dvi *.aux *.ps *~ *.log *.blg *.bbl *.pdf *.ent
